apiVersion: v1
kind: Pod
metadata:
  name: wa-customersmanagerapi
  labels:
    app: wa-customersmanagerapi
spec:
  containers:
    - name: wa-customersmanagerapi-container
      image: 987539726102.dkr.ecr.us-east-1.amazonaws.com/wa-fastfood/wa-fastfoodselfservice.customers_manager_api:latest
      ports:
        - containerPort: 5002
      envFrom:
        - configMapRef:
            name: wa-customersmanagerapi-configmap