apiVersion: v1
kind: Pod
metadata:
  name: wa-customersmanagerapi
  labels:
    app: wa-customersmanagerapi
spec:
  containers:
    - name: wa-customersmanagerapi-container
      image: willmarques/wa-fastfoodselfservice.customers_manager_api:latest
      ports:
        - containerPort: 5002
      envFrom:
        - configMapRef:
            name: wa-customersmanagerapi-configmap