name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      start:
        description: 'Start Unit Tests'
        required: false
        default: 'true'

jobs:
  execute-unit-tests:
    name: Execute Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the solution
        run: dotnet build --no-restore --configuration Release

      - name: Run Tests and Generate Coverage
        run: |
          dotnet test --collect:"XPlat Code Coverage" \
            --results-directory="./TestResults" \
            /p:CoverletOutput="./TestResults/coverage" \
            /p:CoverletOutputFormat="cobertura"

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: Coverage Report
          path: TestResults/coverage.cobertura.xml
