name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: SonarCloud Begin Analysis
        run: |
          dotnet sonarscanner begin \
            /k:"alvarovianello_wa-FastFoodSelfService.customers_manager_api" \
            /o:"alvarovianello" \
            /d:sonar.token=${{ secrets.SONAR_TOKEN }} \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.opencover.reportsPaths="TestResults/coverage.cobertura.xml" \
            /d:sonar.cs.coveragePlugin=opencover

      - name: Build the project
        run: dotnet build wa-FastFoodSelfService.customers_manager_api.sln

      - name: Run Tests and Generate Coverage
        run: |
          dotnet test --collect:"XPlat Code Coverage" \
            --results-directory="./TestResults" \
            --logger:"trx" \
            /p:CoverletOutput="./TestResults/coverage.cobertura.xml" \
            /p:CoverletOutputFormat="cobertura"
          echo "Searching for the coverage file..."
          COVERAGE_PATH=$(find ./TestResults -name "coverage.cobertura.xml" | head -n 1)
          if [ -z "$COVERAGE_PATH" ]; then
            echo "Error: Coverage file not found!"
            exit 1
          else
            echo "Coverage file found at: $COVERAGE_PATH"
            # Copy the coverage file to the desired location
            cp "$COVERAGE_PATH" "./TestResults/coverage.cobertura.xml"
            echo "Coverage file copied to: ./TestResults/coverage.cobertura.xml"
          fi

      - name: Display Coverage File
        run: |
          if [ -f "./TestResults/coverage.cobertura.xml" ]; then
            echo "Coverage file content:"
            cat ./TestResults/coverage.cobertura.xml
          else
            echo "Coverage file not found!"
            exit 1
          fi
	  
      - name: List TestResults Directory
        run: ls -R ./TestResults
	
      - name: SonarCloud End Analysis
        run: dotnet sonarscanner end /d:sonar.token=${{ secrets.SONAR_TOKEN }}
